[language-server.efm]
command = "efm-langserver"

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "markdown"
rulers = [120]
text-width = 120
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
auto-format = true

[[language]]
name = "python"
language-servers = [ 
  { name = "efm", only-features = [ "diagnostics", "format" ] },
  { name = "pyright", except-features = [ "format", "diagnostics" ] }
]
auto-format = true
