[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "markdown"
rulers = [88]
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
auto-format = true

[[language]]
name = "python"
language-server = { command = "pyright" }
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
config = { venv = ".venv/",  venvPath = "." }
